// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: starbeacon/sensor/v1/sensor.proto

package sensorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AckStatus int32

const (
	AckStatus_ACK_STATUS_UNSPECIFIED AckStatus = 0
	AckStatus_ACK_STATUS_ACCEPTED    AckStatus = 1
)

// Enum value maps for AckStatus.
var (
	AckStatus_name = map[int32]string{
		0: "ACK_STATUS_UNSPECIFIED",
		1: "ACK_STATUS_ACCEPTED",
	}
	AckStatus_value = map[string]int32{
		"ACK_STATUS_UNSPECIFIED": 0,
		"ACK_STATUS_ACCEPTED":    1,
	}
)

func (x AckStatus) Enum() *AckStatus {
	p := new(AckStatus)
	*p = x
	return p
}

func (x AckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_starbeacon_sensor_v1_sensor_proto_enumTypes[0].Descriptor()
}

func (AckStatus) Type() protoreflect.EnumType {
	return &file_starbeacon_sensor_v1_sensor_proto_enumTypes[0]
}

func (x AckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckStatus.Descriptor instead.
func (AckStatus) EnumDescriptor() ([]byte, []int) {
	return file_starbeacon_sensor_v1_sensor_proto_rawDescGZIP(), []int{0}
}

type AgentMessageKind int32

const (
	AgentMessageKind_AGENT_MESSAGE_KIND_UNSPECIFIED AgentMessageKind = 0
	AgentMessageKind_AGENT_MESSAGE_KIND_HEARTBEAT   AgentMessageKind = 1
)

// Enum value maps for AgentMessageKind.
var (
	AgentMessageKind_name = map[int32]string{
		0: "AGENT_MESSAGE_KIND_UNSPECIFIED",
		1: "AGENT_MESSAGE_KIND_HEARTBEAT",
	}
	AgentMessageKind_value = map[string]int32{
		"AGENT_MESSAGE_KIND_UNSPECIFIED": 0,
		"AGENT_MESSAGE_KIND_HEARTBEAT":   1,
	}
)

func (x AgentMessageKind) Enum() *AgentMessageKind {
	p := new(AgentMessageKind)
	*p = x
	return p
}

func (x AgentMessageKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentMessageKind) Descriptor() protoreflect.EnumDescriptor {
	return file_starbeacon_sensor_v1_sensor_proto_enumTypes[1].Descriptor()
}

func (AgentMessageKind) Type() protoreflect.EnumType {
	return &file_starbeacon_sensor_v1_sensor_proto_enumTypes[1]
}

func (x AgentMessageKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentMessageKind.Descriptor instead.
func (AgentMessageKind) EnumDescriptor() ([]byte, []int) {
	return file_starbeacon_sensor_v1_sensor_proto_rawDescGZIP(), []int{1}
}

type CommandKind int32

const (
	CommandKind_COMMAND_KIND_UNSPECIFIED   CommandKind = 0
	CommandKind_COMMAND_KIND_HEARTBEAT_ACK CommandKind = 1
)

// Enum value maps for CommandKind.
var (
	CommandKind_name = map[int32]string{
		0: "COMMAND_KIND_UNSPECIFIED",
		1: "COMMAND_KIND_HEARTBEAT_ACK",
	}
	CommandKind_value = map[string]int32{
		"COMMAND_KIND_UNSPECIFIED":   0,
		"COMMAND_KIND_HEARTBEAT_ACK": 1,
	}
)

func (x CommandKind) Enum() *CommandKind {
	p := new(CommandKind)
	*p = x
	return p
}

func (x CommandKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandKind) Descriptor() protoreflect.EnumDescriptor {
	return file_starbeacon_sensor_v1_sensor_proto_enumTypes[2].Descriptor()
}

func (CommandKind) Type() protoreflect.EnumType {
	return &file_starbeacon_sensor_v1_sensor_proto_enumTypes[2]
}

func (x CommandKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandKind.Descriptor instead.
func (CommandKind) EnumDescriptor() ([]byte, []int) {
	return file_starbeacon_sensor_v1_sensor_proto_rawDescGZIP(), []int{2}
}

type EventRecord struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EventId            string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Sequence           uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SourceGenerationId string                 `protobuf:"bytes,3,opt,name=source_generation_id,json=sourceGenerationId,proto3" json:"source_generation_id,omitempty"`
	SourceOffset       uint64                 `protobuf:"varint,4,opt,name=source_offset,json=sourceOffset,proto3" json:"source_offset,omitempty"`
	RecordOrdinal      uint32                 `protobuf:"varint,5,opt,name=record_ordinal,json=recordOrdinal,proto3" json:"record_ordinal,omitempty"`
	EventTime          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	ObservedAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	EventType          string                 `protobuf:"bytes,8,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	RawSha256          []byte                 `protobuf:"bytes,10,opt,name=raw_sha256,json=rawSha256,proto3" json:"raw_sha256,omitempty"`
	EngineRunId        string                 `protobuf:"bytes,11,opt,name=engine_run_id,json=engineRunId,proto3" json:"engine_run_id,omitempty"`
	Payload            []byte                 `protobuf:"bytes,12,opt,name=payload,proto3" json:"payload,omitempty"`
	PayloadSchema      string                 `protobuf:"bytes,13,opt,name=payload_schema,json=payloadSchema,proto3" json:"payload_schema,omitempty"`
	ContentType        string                 `protobuf:"bytes,14,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	PayloadSha256      []byte                 `protobuf:"bytes,15,opt,name=payload_sha256,json=payloadSha256,proto3" json:"payload_sha256,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EventRecord) Reset() {
	*x = EventRecord{}
	mi := &file_starbeacon_sensor_v1_sensor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRecord) ProtoMessage() {}

func (x *EventRecord) ProtoReflect() protoreflect.Message {
	mi := &file_starbeacon_sensor_v1_sensor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRecord.ProtoReflect.Descriptor instead.
func (*EventRecord) Descriptor() ([]byte, []int) {
	return file_starbeacon_sensor_v1_sensor_proto_rawDescGZIP(), []int{0}
}

func (x *EventRecord) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventRecord) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *EventRecord) GetSourceGenerationId() string {
	if x != nil {
		return x.SourceGenerationId
	}
	return ""
}

func (x *EventRecord) GetSourceOffset() uint64 {
	if x != nil {
		return x.SourceOffset
	}
	return 0
}

func (x *EventRecord) GetRecordOrdinal() uint32 {
	if x != nil {
		return x.RecordOrdinal
	}
	return 0
}

func (x *EventRecord) GetEventTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTime
	}
	return nil
}

func (x *EventRecord) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *EventRecord) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventRecord) GetRawSha256() []byte {
	if x != nil {
		return x.RawSha256
	}
	return nil
}

func (x *EventRecord) GetEngineRunId() string {
	if x != nil {
		return x.EngineRunId
	}
	return ""
}

func (x *EventRecord) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EventRecord) GetPayloadSchema() string {
	if x != nil {
		return x.PayloadSchema
	}
	return ""
}

func (x *EventRecord) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *EventRecord) GetPayloadSha256() []byte {
	if x != nil {
		return x.PayloadSha256
	}
	return nil
}

type EventBatch struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	BatchId              string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	SensorId             string                 `protobuf:"bytes,2,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	ProducerEpoch        string                 `protobuf:"bytes,3,opt,name=producer_epoch,json=producerEpoch,proto3" json:"producer_epoch,omitempty"`
	SchemaVersion        string                 `protobuf:"bytes,4,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	RouteToken           string                 `protobuf:"bytes,5,opt,name=route_token,json=routeToken,proto3" json:"route_token,omitempty"`
	Records              []*EventRecord         `protobuf:"bytes,6,rep,name=records,proto3" json:"records,omitempty"`
	SensorRegistrationId string                 `protobuf:"bytes,8,opt,name=sensor_registration_id,json=sensorRegistrationId,proto3" json:"sensor_registration_id,omitempty"`
	StreamId             string                 `protobuf:"bytes,9,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	BatchSha256          []byte                 `protobuf:"bytes,10,opt,name=batch_sha256,json=batchSha256,proto3" json:"batch_sha256,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EventBatch) Reset() {
	*x = EventBatch{}
	mi := &file_starbeacon_sensor_v1_sensor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBatch) ProtoMessage() {}

func (x *EventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_starbeacon_sensor_v1_sensor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBatch.ProtoReflect.Descriptor instead.
func (*EventBatch) Descriptor() ([]byte, []int) {
	return file_starbeacon_sensor_v1_sensor_proto_rawDescGZIP(), []int{1}
}

func (x *EventBatch) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *EventBatch) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *EventBatch) GetProducerEpoch() string {
	if x != nil {
		return x.ProducerEpoch
	}
	return ""
}

func (x *EventBatch) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *EventBatch) GetRouteToken() string {
	if x != nil {
		return x.RouteToken
	}
	return ""
}

func (x *EventBatch) GetRecords() []*EventRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *EventBatch) GetSensorRegistrationId() string {
	if x != nil {
		return x.SensorRegistrationId
	}
	return ""
}

func (x *EventBatch) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *EventBatch) GetBatchSha256() []byte {
	if x != nil {
		return x.BatchSha256
	}
	return nil
}

type SequenceRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	First         uint64                 `protobuf:"varint,1,opt,name=first,proto3" json:"first,omitempty"`
	Last          uint64                 `protobuf:"varint,2,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SequenceRange) Reset() {
	*x = SequenceRange{}
	mi := &file_starbeacon_sensor_v1_sensor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SequenceRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SequenceRange) ProtoMessage() {}

func (x *SequenceRange) ProtoReflect() protoreflect.Message {
	mi := &file_starbeacon_sensor_v1_sensor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SequenceRange.ProtoReflect.Descriptor instead.
func (*SequenceRange) Descriptor() ([]byte, []int) {
	return file_starbeacon_sensor_v1_sensor_proto_rawDescGZIP(), []int{2}
}

func (x *SequenceRange) GetFirst() uint64 {
	if x != nil {
		return x.First
	}
	return 0
}

func (x *SequenceRange) GetLast() uint64 {
	if x != nil {
		return x.Last
	}
	return 0
}

type IngestAck struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	BatchId              string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	ProducerEpoch        string                 `protobuf:"bytes,2,opt,name=producer_epoch,json=producerEpoch,proto3" json:"producer_epoch,omitempty"`
	AcceptedRanges       []*SequenceRange       `protobuf:"bytes,4,rep,name=accepted_ranges,json=acceptedRanges,proto3" json:"accepted_ranges,omitempty"`
	Status               AckStatus              `protobuf:"varint,6,opt,name=status,proto3,enum=starbeacon.sensor.v1.AckStatus" json:"status,omitempty"`
	RetryAfterMs         uint32                 `protobuf:"varint,7,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	ErrorCode            string                 `protobuf:"bytes,8,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	SensorRegistrationId string                 `protobuf:"bytes,9,opt,name=sensor_registration_id,json=sensorRegistrationId,proto3" json:"sensor_registration_id,omitempty"`
	StreamId             string                 `protobuf:"bytes,10,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	BatchSha256          []byte                 `protobuf:"bytes,11,opt,name=batch_sha256,json=batchSha256,proto3" json:"batch_sha256,omitempty"`
	QuarantinedRanges    []*SequenceRange       `protobuf:"bytes,12,rep,name=quarantined_ranges,json=quarantinedRanges,proto3" json:"quarantined_ranges,omitempty"`
	RejectedRecords      []*RejectedRecord      `protobuf:"bytes,13,rep,name=rejected_records,json=rejectedRecords,proto3" json:"rejected_records,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *IngestAck) Reset() {
	*x = IngestAck{}
	mi := &file_starbeacon_sensor_v1_sensor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestAck) ProtoMessage() {}

func (x *IngestAck) ProtoReflect() protoreflect.Message {
	mi := &file_starbeacon_sensor_v1_sensor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestAck.ProtoReflect.Descriptor instead.
func (*IngestAck) Descriptor() ([]byte, []int) {
	return file_starbeacon_sensor_v1_sensor_proto_rawDescGZIP(), []int{3}
}

func (x *IngestAck) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *IngestAck) GetProducerEpoch() string {
	if x != nil {
		return x.ProducerEpoch
	}
	return ""
}

func (x *IngestAck) GetAcceptedRanges() []*SequenceRange {
	if x != nil {
		return x.AcceptedRanges
	}
	return nil
}

func (x *IngestAck) GetStatus() AckStatus {
	if x != nil {
		return x.Status
	}
	return AckStatus_ACK_STATUS_UNSPECIFIED
}

func (x *IngestAck) GetRetryAfterMs() uint32 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

func (x *IngestAck) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *IngestAck) GetSensorRegistrationId() string {
	if x != nil {
		return x.SensorRegistrationId
	}
	return ""
}

func (x *IngestAck) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *IngestAck) GetBatchSha256() []byte {
	if x != nil {
		return x.BatchSha256
	}
	return nil
}

func (x *IngestAck) GetQuarantinedRanges() []*SequenceRange {
	if x != nil {
		return x.QuarantinedRanges
	}
	return nil
}

func (x *IngestAck) GetRejectedRecords() []*RejectedRecord {
	if x != nil {
		return x.RejectedRecords
	}
	return nil
}

type RejectedRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectedRecord) Reset() {
	*x = RejectedRecord{}
	mi := &file_starbeacon_sensor_v1_sensor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectedRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectedRecord) ProtoMessage() {}

func (x *RejectedRecord) ProtoReflect() protoreflect.Message {
	mi := &file_starbeacon_sensor_v1_sensor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectedRecord.ProtoReflect.Descriptor instead.
func (*RejectedRecord) Descriptor() ([]byte, []int) {
	return file_starbeacon_sensor_v1_sensor_proto_rawDescGZIP(), []int{4}
}

func (x *RejectedRecord) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *RejectedRecord) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *RejectedRecord) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

type AgentMessage struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SensorId             string                 `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	MessageId            string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Kind                 AgentMessageKind       `protobuf:"varint,3,opt,name=kind,proto3,enum=starbeacon.sensor.v1.AgentMessageKind" json:"kind,omitempty"`
	CommandId            string                 `protobuf:"bytes,4,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	PayloadSchema        string                 `protobuf:"bytes,5,opt,name=payload_schema,json=payloadSchema,proto3" json:"payload_schema,omitempty"`
	PayloadJson          []byte                 `protobuf:"bytes,6,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	ObservedAt           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	SensorRegistrationId string                 `protobuf:"bytes,8,opt,name=sensor_registration_id,json=sensorRegistrationId,proto3" json:"sensor_registration_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_starbeacon_sensor_v1_sensor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_starbeacon_sensor_v1_sensor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_starbeacon_sensor_v1_sensor_proto_rawDescGZIP(), []int{5}
}

func (x *AgentMessage) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *AgentMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AgentMessage) GetKind() AgentMessageKind {
	if x != nil {
		return x.Kind
	}
	return AgentMessageKind_AGENT_MESSAGE_KIND_UNSPECIFIED
}

func (x *AgentMessage) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *AgentMessage) GetPayloadSchema() string {
	if x != nil {
		return x.PayloadSchema
	}
	return ""
}

func (x *AgentMessage) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

func (x *AgentMessage) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *AgentMessage) GetSensorRegistrationId() string {
	if x != nil {
		return x.SensorRegistrationId
	}
	return ""
}

type PlatformCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Kind          CommandKind            `protobuf:"varint,2,opt,name=kind,proto3,enum=starbeacon.sensor.v1.CommandKind" json:"kind,omitempty"`
	PayloadSchema string                 `protobuf:"bytes,3,opt,name=payload_schema,json=payloadSchema,proto3" json:"payload_schema,omitempty"`
	PayloadJson   []byte                 `protobuf:"bytes,4,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	PayloadSha256 []byte                 `protobuf:"bytes,5,opt,name=payload_sha256,json=payloadSha256,proto3" json:"payload_sha256,omitempty"`
	Signature     []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformCommand) Reset() {
	*x = PlatformCommand{}
	mi := &file_starbeacon_sensor_v1_sensor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformCommand) ProtoMessage() {}

func (x *PlatformCommand) ProtoReflect() protoreflect.Message {
	mi := &file_starbeacon_sensor_v1_sensor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformCommand.ProtoReflect.Descriptor instead.
func (*PlatformCommand) Descriptor() ([]byte, []int) {
	return file_starbeacon_sensor_v1_sensor_proto_rawDescGZIP(), []int{6}
}

func (x *PlatformCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *PlatformCommand) GetKind() CommandKind {
	if x != nil {
		return x.Kind
	}
	return CommandKind_COMMAND_KIND_UNSPECIFIED
}

func (x *PlatformCommand) GetPayloadSchema() string {
	if x != nil {
		return x.PayloadSchema
	}
	return ""
}

func (x *PlatformCommand) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

func (x *PlatformCommand) GetPayloadSha256() []byte {
	if x != nil {
		return x.PayloadSha256
	}
	return nil
}

func (x *PlatformCommand) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *PlatformCommand) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type RouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteRequest) Reset() {
	*x = RouteRequest{}
	mi := &file_starbeacon_sensor_v1_sensor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRequest) ProtoMessage() {}

func (x *RouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_starbeacon_sensor_v1_sensor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRequest.ProtoReflect.Descriptor instead.
func (*RouteRequest) Descriptor() ([]byte, []int) {
	return file_starbeacon_sensor_v1_sensor_proto_rawDescGZIP(), []int{7}
}

func (x *RouteRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Partition     string                 `protobuf:"bytes,3,opt,name=partition,proto3" json:"partition,omitempty"`
	StreamId      string                 `protobuf:"bytes,4,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_starbeacon_sensor_v1_sensor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_starbeacon_sensor_v1_sensor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_starbeacon_sensor_v1_sensor_proto_rawDescGZIP(), []int{8}
}

func (x *Route) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Route) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Route) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *Route) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *Route) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

var File_starbeacon_sensor_v1_sensor_proto protoreflect.FileDescriptor

const file_starbeacon_sensor_v1_sensor_proto_rawDesc = "" +
	"\n" +
	"!starbeacon/sensor/v1/sensor.proto\x12\x14starbeacon.sensor.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb7\x04\n" +
	"\vEventRecord\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x120\n" +
	"\x14source_generation_id\x18\x03 \x01(\tR\x12sourceGenerationId\x12#\n" +
	"\rsource_offset\x18\x04 \x01(\x04R\fsourceOffset\x12%\n" +
	"\x0erecord_ordinal\x18\x05 \x01(\rR\rrecordOrdinal\x129\n" +
	"\n" +
	"event_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\teventTime\x12;\n" +
	"\vobserved_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12\x1d\n" +
	"\n" +
	"event_type\x18\b \x01(\tR\teventType\x12\x1d\n" +
	"\n" +
	"raw_sha256\x18\n" +
	" \x01(\fR\trawSha256\x12\"\n" +
	"\rengine_run_id\x18\v \x01(\tR\vengineRunId\x12\x18\n" +
	"\apayload\x18\f \x01(\fR\apayload\x12%\n" +
	"\x0epayload_schema\x18\r \x01(\tR\rpayloadSchema\x12!\n" +
	"\fcontent_type\x18\x0e \x01(\tR\vcontentType\x12%\n" +
	"\x0epayload_sha256\x18\x0f \x01(\fR\rpayloadSha256J\x04\b\t\x10\n" +
	"R\beve_json\"\x83\x03\n" +
	"\n" +
	"EventBatch\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12\x1b\n" +
	"\tsensor_id\x18\x02 \x01(\tR\bsensorId\x12%\n" +
	"\x0eproducer_epoch\x18\x03 \x01(\tR\rproducerEpoch\x12%\n" +
	"\x0eschema_version\x18\x04 \x01(\tR\rschemaVersion\x12\x1f\n" +
	"\vroute_token\x18\x05 \x01(\tR\n" +
	"routeToken\x12;\n" +
	"\arecords\x18\x06 \x03(\v2!.starbeacon.sensor.v1.EventRecordR\arecords\x124\n" +
	"\x16sensor_registration_id\x18\b \x01(\tR\x14sensorRegistrationId\x12\x1b\n" +
	"\tstream_id\x18\t \x01(\tR\bstreamId\x12!\n" +
	"\fbatch_sha256\x18\n" +
	" \x01(\fR\vbatchSha256J\x04\b\a\x10\bR\x15resume_after_sequence\"9\n" +
	"\rSequenceRange\x12\x14\n" +
	"\x05first\x18\x01 \x01(\x04R\x05first\x12\x12\n" +
	"\x04last\x18\x02 \x01(\x04R\x04last\"\xe2\x04\n" +
	"\tIngestAck\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12%\n" +
	"\x0eproducer_epoch\x18\x02 \x01(\tR\rproducerEpoch\x12L\n" +
	"\x0faccepted_ranges\x18\x04 \x03(\v2#.starbeacon.sensor.v1.SequenceRangeR\x0eacceptedRanges\x127\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1f.starbeacon.sensor.v1.AckStatusR\x06status\x12$\n" +
	"\x0eretry_after_ms\x18\a \x01(\rR\fretryAfterMs\x12\x1d\n" +
	"\n" +
	"error_code\x18\b \x01(\tR\terrorCode\x124\n" +
	"\x16sensor_registration_id\x18\t \x01(\tR\x14sensorRegistrationId\x12\x1b\n" +
	"\tstream_id\x18\n" +
	" \x01(\tR\bstreamId\x12!\n" +
	"\fbatch_sha256\x18\v \x01(\fR\vbatchSha256\x12R\n" +
	"\x12quarantined_ranges\x18\f \x03(\v2#.starbeacon.sensor.v1.SequenceRangeR\x11quarantinedRanges\x12O\n" +
	"\x10rejected_records\x18\r \x03(\v2$.starbeacon.sensor.v1.RejectedRecordR\x0frejectedRecordsJ\x04\b\x03\x10\x04J\x04\b\x05\x10\x06R\x10accepted_throughR\x0emissing_ranges\"i\n" +
	"\x0eRejectedRecord\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\"\xe2\x02\n" +
	"\fAgentMessage\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\tR\bsensorId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12:\n" +
	"\x04kind\x18\x03 \x01(\x0e2&.starbeacon.sensor.v1.AgentMessageKindR\x04kind\x12\x1d\n" +
	"\n" +
	"command_id\x18\x04 \x01(\tR\tcommandId\x12%\n" +
	"\x0epayload_schema\x18\x05 \x01(\tR\rpayloadSchema\x12!\n" +
	"\fpayload_json\x18\x06 \x01(\fR\vpayloadJson\x12;\n" +
	"\vobserved_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x124\n" +
	"\x16sensor_registration_id\x18\b \x01(\tR\x14sensorRegistrationId\"\xb1\x02\n" +
	"\x0fPlatformCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x125\n" +
	"\x04kind\x18\x02 \x01(\x0e2!.starbeacon.sensor.v1.CommandKindR\x04kind\x12%\n" +
	"\x0epayload_schema\x18\x03 \x01(\tR\rpayloadSchema\x12!\n" +
	"\fpayload_json\x18\x04 \x01(\fR\vpayloadJson\x12%\n" +
	"\x0epayload_sha256\x18\x05 \x01(\fR\rpayloadSha256\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"+\n" +
	"\fRouteRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\"\xb0\x01\n" +
	"\x05Route\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1c\n" +
	"\tpartition\x18\x03 \x01(\tR\tpartition\x12\x1b\n" +
	"\tstream_id\x18\x04 \x01(\tR\bstreamId\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt*@\n" +
	"\tAckStatus\x12\x1a\n" +
	"\x16ACK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ACK_STATUS_ACCEPTED\x10\x01*X\n" +
	"\x10AgentMessageKind\x12\"\n" +
	"\x1eAGENT_MESSAGE_KIND_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cAGENT_MESSAGE_KIND_HEARTBEAT\x10\x01*K\n" +
	"\vCommandKind\x12\x1c\n" +
	"\x18COMMAND_KIND_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCOMMAND_KIND_HEARTBEAT_ACK\x10\x012\x8d\x02\n" +
	"\rSensorService\x12U\n" +
	"\fUploadEvents\x12 .starbeacon.sensor.v1.EventBatch\x1a\x1f.starbeacon.sensor.v1.IngestAck(\x010\x01\x12X\n" +
	"\aControl\x12\".starbeacon.sensor.v1.AgentMessage\x1a%.starbeacon.sensor.v1.PlatformCommand(\x010\x01\x12K\n" +
	"\bGetRoute\x12\".starbeacon.sensor.v1.RouteRequest\x1a\x1b.starbeacon.sensor.v1.RouteB5Z3github.com/kkx600/StarBeacon/api/sensor/v1;sensorv1b\x06proto3"

var (
	file_starbeacon_sensor_v1_sensor_proto_rawDescOnce sync.Once
	file_starbeacon_sensor_v1_sensor_proto_rawDescData []byte
)

func file_starbeacon_sensor_v1_sensor_proto_rawDescGZIP() []byte {
	file_starbeacon_sensor_v1_sensor_proto_rawDescOnce.Do(func() {
		file_starbeacon_sensor_v1_sensor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_starbeacon_sensor_v1_sensor_proto_rawDesc), len(file_starbeacon_sensor_v1_sensor_proto_rawDesc)))
	})
	return file_starbeacon_sensor_v1_sensor_proto_rawDescData
}

var file_starbeacon_sensor_v1_sensor_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_starbeacon_sensor_v1_sensor_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_starbeacon_sensor_v1_sensor_proto_goTypes = []any{
	(AckStatus)(0),                // 0: starbeacon.sensor.v1.AckStatus
	(AgentMessageKind)(0),         // 1: starbeacon.sensor.v1.AgentMessageKind
	(CommandKind)(0),              // 2: starbeacon.sensor.v1.CommandKind
	(*EventRecord)(nil),           // 3: starbeacon.sensor.v1.EventRecord
	(*EventBatch)(nil),            // 4: starbeacon.sensor.v1.EventBatch
	(*SequenceRange)(nil),         // 5: starbeacon.sensor.v1.SequenceRange
	(*IngestAck)(nil),             // 6: starbeacon.sensor.v1.IngestAck
	(*RejectedRecord)(nil),        // 7: starbeacon.sensor.v1.RejectedRecord
	(*AgentMessage)(nil),          // 8: starbeacon.sensor.v1.AgentMessage
	(*PlatformCommand)(nil),       // 9: starbeacon.sensor.v1.PlatformCommand
	(*RouteRequest)(nil),          // 10: starbeacon.sensor.v1.RouteRequest
	(*Route)(nil),                 // 11: starbeacon.sensor.v1.Route
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_starbeacon_sensor_v1_sensor_proto_depIdxs = []int32{
	12, // 0: starbeacon.sensor.v1.EventRecord.event_time:type_name -> google.protobuf.Timestamp
	12, // 1: starbeacon.sensor.v1.EventRecord.observed_at:type_name -> google.protobuf.Timestamp
	3,  // 2: starbeacon.sensor.v1.EventBatch.records:type_name -> starbeacon.sensor.v1.EventRecord
	5,  // 3: starbeacon.sensor.v1.IngestAck.accepted_ranges:type_name -> starbeacon.sensor.v1.SequenceRange
	0,  // 4: starbeacon.sensor.v1.IngestAck.status:type_name -> starbeacon.sensor.v1.AckStatus
	5,  // 5: starbeacon.sensor.v1.IngestAck.quarantined_ranges:type_name -> starbeacon.sensor.v1.SequenceRange
	7,  // 6: starbeacon.sensor.v1.IngestAck.rejected_records:type_name -> starbeacon.sensor.v1.RejectedRecord
	1,  // 7: starbeacon.sensor.v1.AgentMessage.kind:type_name -> starbeacon.sensor.v1.AgentMessageKind
	12, // 8: starbeacon.sensor.v1.AgentMessage.observed_at:type_name -> google.protobuf.Timestamp
	2,  // 9: starbeacon.sensor.v1.PlatformCommand.kind:type_name -> starbeacon.sensor.v1.CommandKind
	12, // 10: starbeacon.sensor.v1.PlatformCommand.expires_at:type_name -> google.protobuf.Timestamp
	12, // 11: starbeacon.sensor.v1.Route.expires_at:type_name -> google.protobuf.Timestamp
	4,  // 12: starbeacon.sensor.v1.SensorService.UploadEvents:input_type -> starbeacon.sensor.v1.EventBatch
	8,  // 13: starbeacon.sensor.v1.SensorService.Control:input_type -> starbeacon.sensor.v1.AgentMessage
	10, // 14: starbeacon.sensor.v1.SensorService.GetRoute:input_type -> starbeacon.sensor.v1.RouteRequest
	6,  // 15: starbeacon.sensor.v1.SensorService.UploadEvents:output_type -> starbeacon.sensor.v1.IngestAck
	9,  // 16: starbeacon.sensor.v1.SensorService.Control:output_type -> starbeacon.sensor.v1.PlatformCommand
	11, // 17: starbeacon.sensor.v1.SensorService.GetRoute:output_type -> starbeacon.sensor.v1.Route
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_starbeacon_sensor_v1_sensor_proto_init() }
func file_starbeacon_sensor_v1_sensor_proto_init() {
	if File_starbeacon_sensor_v1_sensor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_starbeacon_sensor_v1_sensor_proto_rawDesc), len(file_starbeacon_sensor_v1_sensor_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_starbeacon_sensor_v1_sensor_proto_goTypes,
		DependencyIndexes: file_starbeacon_sensor_v1_sensor_proto_depIdxs,
		EnumInfos:         file_starbeacon_sensor_v1_sensor_proto_enumTypes,
		MessageInfos:      file_starbeacon_sensor_v1_sensor_proto_msgTypes,
	}.Build()
	File_starbeacon_sensor_v1_sensor_proto = out.File
	file_starbeacon_sensor_v1_sensor_proto_goTypes = nil
	file_starbeacon_sensor_v1_sensor_proto_depIdxs = nil
}
