<script setup lang="ts">
import {computed,reactive,ref} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {message} from 'ant-design-vue'
import {SafetyCertificateOutlined,UserOutlined,LockOutlined,ArrowLeftOutlined,CheckCircleOutlined} from '@ant-design/icons-vue'
import type {FormInstance} from 'ant-design-vue'
const route=useRoute();const router=useRouter();const mode=computed(()=>String(route.params.mode));const formRef=ref<FormInstance>();const busy=ref(false)
const form=reactive({account:'analyst@example.test',password:'',code:'',remember:true,email:''})
const title=computed(()=>mode.value==='mfa'?'多因素认证':mode.value==='reset'?'找回密码':mode.value==='expired'?'会话已过期':'登录星烽 StarBeacon')
const description=computed(()=>mode.value==='mfa'?'输入认证器中的 6 位验证码以继续。':mode.value==='reset'?'填写账号邮箱，获取账号恢复指引。':mode.value==='expired'?'当前认证会话已失效，重新登录后继续处理。':'使用组织账号进入安全运营工作空间。')
async function submit(){try{await formRef.value?.validate();if(mode.value==='mfa'&&!/^\d{6}$/.test(form.code)){message.error('请输入 6 位数字验证码。');return}busy.value=true;await new Promise(resolve=>setTimeout(resolve,180));if(mode.value==='reset'){message.success('合成恢复指引已确认，未发送邮件。');void router.push('/auth/login')}else if(mode.value==='mfa')void router.push('/page/overview');else void router.push('/auth/mfa')}catch{}finally{busy.value=false}}
</script>
<template>
  <div class="auth-page"><header><button class="brand" @click="router.push('/catalog')"><span class="brand-symbol"><SafetyCertificateOutlined/></span><span class="brand-copy"><b>星烽 <span>StarBeacon</span></b><small>态势感知系统</small></span></button><router-link to="/catalog">浏览原型页面</router-link></header><div class="auth-layout"><section class="auth-intro"><h1>让每一次研判<br/>都有证据可循。</h1><p>从网络观测到告警调查、受控响应与复盘，将风险和依据放在同一条工作路径上。</p><div class="auth-principles"><div><CheckCircleOutlined/><span>观测事实与安全结论分开记录</span></div><div><CheckCircleOutlined/><span>受控响应具备授权、回执和撤销</span></div><div><CheckCircleOutlined/><span>组织、对象与数据范围一致管理</span></div></div><small>StarBeacon — stellar early-warning for security posture.</small></section><section class="auth-card"><h2>{{title}}</h2><p>{{description}}</p><a-alert message="交互原型 · 使用合成账号，不验证真实凭据。" type="info" show-icon/><a-form ref="formRef" :model="form" layout="vertical" @finish="submit"><template v-if="mode==='expired'"><div class="session-expired"><LockOutlined/><p>认证期限：60 分钟（示例）<br/>当前业务对象不会因会话过期被删除。</p><a-button type="primary" block @click="router.push('/auth/login')">重新登录</a-button></div></template><template v-else><template v-if="mode==='mfa'"><a-form-item label="认证验证码" name="code" :rules="[{required:true,message:'请输入认证验证码'}]"><a-input v-model:value="form.code" maxlength="6" inputmode="numeric" autocomplete="one-time-code" size="large" placeholder="输入 6 位数字"/></a-form-item><small class="field-hint">原型中任意 6 位数字均可继续。正式环境由认证服务验证。</small></template><template v-else-if="mode==='reset'"><a-form-item label="账号邮箱" name="email" :rules="[{required:true,type:'email',message:'请输入有效的账号邮箱'}]"><a-input v-model:value="form.email" size="large" placeholder="name@example.test"/></a-form-item></template><template v-else><a-form-item label="组织账号" name="account" :rules="[{required:true,message:'请输入组织账号'}]"><a-input v-model:value="form.account" size="large" autocomplete="username"><template #prefix><UserOutlined/></template></a-input></a-form-item><a-form-item label="密码" name="password" :rules="[{required:true,message:'请输入用于演示的密码'}]"><a-input-password v-model:value="form.password" size="large" autocomplete="current-password" placeholder="输入演示密码"><template #prefix><LockOutlined/></template></a-input-password></a-form-item><div class="login-options"><a-checkbox v-model:checked="form.remember">记住账号</a-checkbox><router-link to="/auth/reset">忘记密码</router-link></div></template><a-button type="primary" size="large" block :loading="busy" @click="submit">{{mode==='mfa'?'验证并进入':mode==='reset'?'获取恢复指引':'登录'}}</a-button><a-divider v-if="mode==='login'">组织身份</a-divider><a-button v-if="mode==='login'" size="large" block @click="router.push('/auth/mfa')">使用组织 SSO</a-button><router-link v-else to="/auth/login" class="back-to-login"><ArrowLeftOutlined/>返回登录</router-link></template></a-form><div class="auth-card-footnote">受租户授权、MFA 与会话策略保护</div></section></div><footer>星烽 StarBeacon · 合成示例环境</footer></div>
</template>
