<script setup lang="ts">
import {computed,ref,watch} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {collectorPages} from '../data/collector'
import type {CollectorAction,CollectorInterface,CollectorTask} from '../data/collector'
import {useCollector} from '../composables/useCollector'
import {usePreview} from '../composables/usePreview'
import PageHeader from '../components/PageHeader.vue'
import MetricBar from '../components/MetricBar.vue'
import StatePanel from '../components/StatePanel.vue'
import StatusTag from '../components/StatusTag.vue'
import ReplayPreview from '../components/ReplayPreview.vue'
import {formatQuantity} from '../../../web/packages/shared/src/utils/format'
import CollectorForm from '../components/CollectorForm.vue'
const route=useRoute();const router=useRouter();const {state,setState}=usePreview();const {state:collector,device}=useCollector()
const page=computed(()=>collectorPages.find(item=>item.id===route.params.id))
const detailOpen=ref(false);const actionOpen=ref(false);const selected=ref<CollectorInterface|CollectorTask>();const action=ref<CollectorAction>('network');const localTab=ref('interfaces');const keyword=ref('');const statusFilter=ref('全部状态')
const pageTabs:Record<string,string[]>={network:['interfaces','capture','replay-samples','replay-tasks'],updates:['rules','system'],maintenance:['services','audits']}
watch(()=>[page.value?.id,route.query.view],()=>{const tabs=pageTabs[page.value?.id??'']??['interfaces'];const value=route.query.view;localTab.value=typeof value==='string'&&tabs.includes(value)?value:tabs[0]!},{immediate:true})
function changeTab(value:string|number){const next=String(value);const tabs=pageTabs[page.value?.id??'']??[];if(!tabs.includes(next)||next===localTab.value)return;void router.push({query:{...route.query,view:next===tabs[0]?undefined:next}})}
const serviceId=ref('suricata')
const defaultActions:Record<string,CollectorAction>={overview:'service',network:'network',connection:'connection',updates:'rule-sync',maintenance:'maintenance'}
const primaryAction=computed<CollectorAction>(()=>page.value?.id==='updates'&&localTab.value==='system'?'upgrade':defaultActions[page.value?.id??'overview']??'service')
const primaryLabel=computed(()=>primaryAction.value==='upgrade'?'创建升级申请':page.value?.primary??'')
const nicColumns=[{title:'网卡 / MAC 地址',key:'identity',width:215},{title:'用途',dataIndex:'role',width:100},{title:'链路状态',key:'status',width:130},{title:'IP 地址',key:'address',width:185},{title:'速率 / MTU',key:'speed',width:140},{title:'观测流量',dataIndex:'rx',width:140},{title:'操作',key:'action',width:80}]
const taskColumns=[{title:'任务',key:'identity',width:175},{title:'来源',dataIndex:'source',width:165},{title:'目标 / 对象',dataIndex:'target',width:220},{title:'状态',key:'status',width:180},{title:'创建时间',dataIndex:'time',width:170},{title:'操作',key:'action',width:80}]
const servicesColumns=[{title:'服务',dataIndex:'name',width:190},{title:'版本',dataIndex:'version',width:160},{title:'状态',key:'status',width:130},{title:'职责',dataIndex:'description',width:350},{title:'操作',key:'action',width:85}]
const auditColumns=[{title:'时间',dataIndex:'time',width:170},{title:'操作者',dataIndex:'actor',width:195},{title:'操作',dataIndex:'action',width:185},{title:'对象',dataIndex:'object',width:210},{title:'结果',dataIndex:'result',width:245}]
const interfaces=computed(()=>collector.interfaces.filter(item=>`${item.name} ${item.mac} ${item.ipv4} ${item.role}`.includes(keyword.value.trim())&&(statusFilter.value==='全部状态'||item.status===statusFilter.value)))
const tasks=computed(()=>collector.tasks.filter(item=>`${item.name} ${item.id} ${item.target} ${item.source}`.includes(keyword.value.trim())&&(statusFilter.value==='全部状态'||item.status===statusFilter.value)))
const hasFilters=computed(()=>!!keyword.value.trim()||statusFilter.value!=='全部状态')
const selectedNic=computed(()=>selected.value&&'mac' in selected.value?selected.value:undefined)
const selectedTask=computed(()=>selected.value&&'steps' in selected.value?selected.value:undefined)
const metrics=computed(()=>[{label:'CPU 使用率',value:'22',suffix:'%',note:'同一设备遥测快照'},{label:'内存使用率',value:'35',suffix:'%',note:'16 GiB 总内存'},{label:'磁盘使用率',value:'48',suffix:'%',note:'示例可分配缓冲 300 GiB'},{label:'镜像流量',value:'482',suffix:'Mbit/s',note:'eth0 · 丢包率 0.00%'}])
watch(()=>[page.value?.id,state.value,localTab.value],()=>{detailOpen.value=state.value==='detail';actionOpen.value=state.value==='action';action.value=primaryAction.value;selected.value=page.value?.id==='network'?collector.interfaces[0]:page.value?.id==='updates'?collector.tasks[1]:undefined;keyword.value='';statusFilter.value='全部状态'},{immediate:true})
function openAction(value:CollectorAction,service='suricata'){action.value=value;serviceId.value=service;actionOpen.value=true}
function showDetail(item?:CollectorInterface|CollectorTask){selected.value=item;detailOpen.value=true}
function closeDetail(){detailOpen.value=false;if(state.value==='detail')setState('data')}
function closeAction(){actionOpen.value=false;if(state.value==='action')setState('data')}
async function onRequested(task:CollectorTask){actionOpen.value=false;if(state.value==='action')await router.replace({query:{...route.query,state:'data'}});selected.value=task;detailOpen.value=true}
function clearFilters(){keyword.value='';statusFilter.value='全部状态'}
</script>
<template>
  <div v-if="page" class="page-surface" :data-page-id="`collector-${page.id}`" :data-page-state="state">
    <PageHeader :title="page.title" :description="page.description"><a-button v-if="!localTab.startsWith('replay-')" @click="showDetail()">{{page.id==='network'?'查看配置':page.id==='updates'?'版本明细':'查看详情'}}</a-button><a-button v-if="!localTab.startsWith('replay-')" type="primary" @click="openAction(primaryAction)">{{primaryLabel}}</a-button></PageHeader>
    <div class="collector-context"><span><b>{{device.name}}</b> · {{device.id}}</span><span>{{device.zone}} · 快照 {{device.snapshot}}</span></div>
    <nav v-if="page.id==='network'" class="workspace-views" aria-label="网络与采集功能"><a-tabs :active-key="localTab" @change="changeTab"><a-tab-pane key="interfaces" tab="网卡与地址"/><a-tab-pane key="capture" tab="采集配置"/><a-tab-pane key="replay-samples" tab="重放样本"/><a-tab-pane key="replay-tasks" tab="重放任务"/></a-tabs></nav>
    <ReplayPreview v-if="page.id==='network'&&localTab.startsWith('replay-')" local embedded :tasks="localTab==='replay-tasks'" :state="state" @state="setState" @view="changeTab"/>
    <StatePanel v-else-if="state==='loading'||state==='error'" :state="state" :title="state==='error'?'采集器数据暂时无法加载':undefined" :description="state==='error'?'本地管理服务未返回数据。当前配置与执行结果未知，请重试或检查管理服务。':undefined" @action="setState('data')"/>
    <StatePanel v-else-if="state==='empty'" state="empty" :title="({overview:'尚未完成采集器初始化',network:'尚未配置采集网络',connection:'尚未注册主控平台',updates:'暂无同步或升级任务',maintenance:'暂无本地维护记录'})[page.id]" :description="({overview:'完成管理网络、镜像网卡和平台接入后，查看本机运行状态。',network:'选择管理口与镜像采集口，设置地址并校验配置。',connection:'配置主控平台地址和受信 CA，使用平台签发的注册密钥注册设备。',updates:'设备注册后可接收平台任务；离线环境可通过签名制品包执行升级。',maintenance:'时间、缓冲和服务维护操作会在此形成审计记录。'})[page.id]" :action="page.id==='overview'?'配置管理网络':page.primary" @action="openAction(page.id==='overview'?'network':defaultActions[page.id]!)"/>
    <template v-else>
      <template v-if="page.id==='overview'">
        <MetricBar :items="metrics"/>
        <section class="panel collector-section"><div class="panel-heading"><h2>采集与上报链路</h2><StatusTag value="在线（示例）"/></div><a-descriptions bordered :column="{xs:1,sm:1,md:2}" size="small"><a-descriptions-item label="采集模式">旁路镜像 · {{collector.capture.backend}}</a-descriptions-item><a-descriptions-item label="镜像采集口">{{collector.capture.interfaces.join('、')}}</a-descriptions-item><a-descriptions-item label="管理口">{{collector.network.interface}} · {{collector.network.ipv4}}</a-descriptions-item><a-descriptions-item label="主控平台">{{collector.connection.host}}:{{collector.connection.port}}</a-descriptions-item><a-descriptions-item label="引擎 / 规则">{{collector.engineActive}} / {{collector.ruleActive}}</a-descriptions-item><a-descriptions-item label="心跳 / 证书">{{collector.connection.heartbeat}} 秒 / {{collector.certificate}}</a-descriptions-item><a-descriptions-item label="事件 WAL">0 条待上传 · 已确认水位 demo-eve-094500</a-descriptions-item><a-descriptions-item label="PCAP 归档">无上传积压（示例）· 对象留存 180 天</a-descriptions-item><a-descriptions-item label="本机时钟">误差 +3 ms（示例）· {{collector.maintenance.timezone}}</a-descriptions-item><a-descriptions-item label="联动权限">未授权本机执行设备写动作</a-descriptions-item></a-descriptions><p class="field-hint">心跳、采集健康和数据持久确认是不同状态。当前为合成快照，不代表实时监控或性能验收。</p></section>
        <section class="panel table-panel"><div class="table-toolbar"><h2>最近任务</h2><router-link to="/collector/updates">查看同步与升级</router-link></div><a-table :columns="taskColumns" :data-source="collector.tasks.slice(0,4)" row-key="id" :pagination="false" :scroll="{x:1050}" size="middle"><template #bodyCell="{column,record}"><template v-if="column.key==='identity'"><button class="record-link" @click="showDetail(record)">{{record.name}}</button><small class="row-id">{{record.id}}</small></template><StatusTag v-else-if="column.key==='status'" :value="record.status"/><a-button v-else-if="column.key==='action'" type="link" size="small" @click="showDetail(record)">查看</a-button></template></a-table></section>
      </template>
      <template v-else-if="page.id==='network'">

        <template v-if="localTab==='interfaces'">
          <section class="panel collector-config-strip"><div><span>管理口</span><b>{{collector.network.interface}} · {{collector.network.ipv4}}</b></div><div><span>IPv4 网关</span><b>{{collector.network.gateway}}</b></div><div><span>DNS</span><b>{{collector.network.dns}}</b></div><div><span>变更确认窗口</span><b>{{collector.network.rollbackSeconds}} 秒</b></div></section>
          <section class="panel filter-panel"><div class="collector-filter"><a-input v-model:value="keyword" aria-label="检索网卡" placeholder="网卡、MAC、IP 或用途" allow-clear/><a-select v-model:value="statusFilter" aria-label="网卡链路状态" :options="['全部状态','链路正常','链路断开','本机回环'].map(value=>({value,label:value}))"/><a-button @click="clearFilters">清除筛选</a-button></div></section>
          <section class="panel table-panel"><div class="table-toolbar"><h2>本机网卡 <span class="muted">{{interfaces.length}} 张</span></h2><a-button @click="openAction('capture')">选择镜像网卡</a-button></div><a-table :columns="nicColumns" :data-source="interfaces" row-key="id" :pagination="false" :scroll="{x:990}" size="middle"><template #bodyCell="{column,record}"><template v-if="column.key==='identity'"><button class="record-link" @click="showDetail(record)">{{record.name}}</button><small class="row-id">{{record.mac}}</small></template><StatusTag v-else-if="column.key==='status'" :value="record.status"/><template v-else-if="column.key==='address'">{{record.ipv4}}<small class="row-id">IPv6：{{record.ipv6}}</small></template><template v-else-if="column.key==='speed'">{{formatQuantity(record.speed)}}<small class="row-id">MTU {{record.mtu}}</small></template><span v-else-if="column.dataIndex==='rx'" class="tabular">{{formatQuantity(record.rx)}}</span><a-button v-else-if="column.key==='action'" type="link" size="small" @click="showDetail(record)">查看</a-button></template><template #emptyText><a-empty :description="hasFilters?'暂无符合条件的网卡':'尚未发现可用网卡'"><a-button v-if="hasFilters" @click="clearFilters">清除筛选</a-button></a-empty></template></a-table></section>
          <p class="collector-footnote">镜像口不配置业务 IP、网关或 DHCP。VLAN、Bond 和虚拟接口需按设备能力识别，当前样机仅提供物理网卡与回环接口。</p>
        </template>
        <section v-else class="panel collector-section"><div class="panel-heading"><h2>实际采集配置</h2><a-button @click="openAction('capture')">编辑采集配置</a-button></div><a-descriptions bordered :column="{xs:1,sm:1,md:2}" size="small"><a-descriptions-item label="镜像采集口">{{collector.capture.interfaces.join('、')}}</a-descriptions-item><a-descriptions-item label="捕获后端 / 部署模式">AF_PACKET / 旁路</a-descriptions-item><a-descriptions-item label="HOME_NET">{{collector.capture.homeNet}}</a-descriptions-item><a-descriptions-item label="BPF 过滤">{{collector.capture.bpf||'不额外过滤'}}</a-descriptions-item><a-descriptions-item label="捕获长度上限">{{collector.capture.snaplen}} 字节</a-descriptions-item><a-descriptions-item label="混杂模式">{{collector.capture.promisc?'开启':'关闭'}}</a-descriptions-item><a-descriptions-item label="线程 / cluster-id">每接口 {{collector.capture.threads}} 线程 / 从 {{collector.capture.clusterBase}} 顺序分配</a-descriptions-item><a-descriptions-item label="GRO / LRO（eth0）">关闭 / 关闭（示例回读）</a-descriptions-item><a-descriptions-item label="TCP 重组深度">{{collector.capture.streamMiB}} MiB</a-descriptions-item><a-descriptions-item label="HTTP / 文件深度">{{collector.capture.httpMiB}} / {{collector.capture.fileMiB}} MiB</a-descriptions-item></a-descriptions><a-alert type="info" show-icon class="page-notice" message="捕获长度与检测深度分别生效。深度限制、缺包和 TLS 密文会影响检测；保存完整原包不代表已检查全部明文。"/><p class="field-hint">BPF、网卡卸载、RSS 与 NUMA 设置需由实际引擎和驱动校验。配置变化可能重启捕获进程，必须保留检测缺口与流量回读。</p></section>
      </template>
      <template v-else-if="page.id==='connection'">
        <section class="panel collector-section"><div class="panel-heading"><h2>主控平台连接</h2><StatusTag value="已连接（示例）"/></div><a-descriptions bordered :column="{xs:1,sm:1,md:2}" size="small"><a-descriptions-item label="上报地址">{{collector.connection.host}}:{{collector.connection.port}}</a-descriptions-item><a-descriptions-item label="TLS 服务名">{{collector.connection.serverName}}</a-descriptions-item><a-descriptions-item label="通信认证">双向 TLS · 强制校验服务端身份</a-descriptions-item><a-descriptions-item label="受信 CA / 本机证书引用">{{collector.connection.caRef}} / {{collector.connection.clientRef}}</a-descriptions-item><a-descriptions-item label="设备身份">{{device.id}} · {{device.tenant}}</a-descriptions-item><a-descriptions-item label="制品地址">{{collector.connection.artifactUrl}}</a-descriptions-item><a-descriptions-item label="心跳周期">{{collector.connection.heartbeat}} 秒</a-descriptions-item><a-descriptions-item label="批次 / 重试起始间隔">{{collector.connection.batch}} 条 / {{collector.connection.retrySeconds}} 秒</a-descriptions-item><a-descriptions-item label="事件上报确认">平台持久接收水位 demo-eve-094500（示例）</a-descriptions-item><a-descriptions-item label="PCAP 上传">签名授权上传 · 不保存对象管理员密钥</a-descriptions-item></a-descriptions><div class="collector-action-row"><a-button @click="openAction('enroll')">使用注册密钥</a-button><a-button @click="showDetail()">查看证书</a-button><a-button @click="openAction('certificate')">申请证书轮换</a-button></div></section>
        <section class="panel collector-section"><div class="panel-heading"><h2>注册与身份边界</h2></div><p>注册密钥由主平台签发，绑定租户、站点、网络域与有效期，使用后换取本机设备证书。平台的设备记录不等于注册认证已经完成。</p><p>当前设备已注册。重新注册或迁移前需要核对待上传事件、PCAP 归属和活动响应动作；这些操作由主控平台授权，本地不能直接修改租户。</p><p class="field-hint">注册密钥为仅写字段；证书私钥不回显、不导出，不进入任务摘要和日志。此原型不进行真实连接或认证。</p></section>
      </template>
      <template v-else-if="page.id==='updates'">
        <nav class="workspace-views" aria-label="规则与升级功能"><a-tabs :active-key="localTab" @change="changeTab"><a-tab-pane key="rules" tab="规则同步"/><a-tab-pane key="system" tab="系统升级"/></a-tabs></nav>
        <section class="panel collector-section"><div class="panel-heading"><h2>{{localTab==='rules'?'规则版本':'系统版本'}}</h2></div><a-descriptions bordered :column="{xs:1,sm:1,md:2}" size="small"><template v-if="localTab==='rules'"><a-descriptions-item label="平台目标规则包">{{collector.ruleDesired}}</a-descriptions-item><a-descriptions-item label="实际生效规则包">{{collector.ruleActive}}</a-descriptions-item><a-descriptions-item label="实际规则数 / 引擎">12840 条 / {{collector.engineActive}}</a-descriptions-item><a-descriptions-item label="同步状态"><StatusTag value="存在待同步版本"/></a-descriptions-item><a-descriptions-item label="规则来源">平台签名制品 · 不允许本地覆盖已发布包</a-descriptions-item><a-descriptions-item label="同步方式">{{collector.syncMode}} · 每 {{collector.syncMinutes}} 分钟核对版本</a-descriptions-item><a-descriptions-item label="自动重载">{{collector.autoApply?'校验通过后允许':'需人工申请'}} · 仍需回读实际版本</a-descriptions-item></template><template v-else><a-descriptions-item label="实际 Agent">{{collector.agentActive}}</a-descriptions-item><a-descriptions-item label="平台目标 Agent">{{collector.agentDesired}}</a-descriptions-item><a-descriptions-item label="实际引擎">{{collector.engineActive}}</a-descriptions-item><a-descriptions-item label="操作系统 / 架构">Linux x86_64（示例）</a-descriptions-item><a-descriptions-item label="系统升级范围">Agent、检测引擎、受支持系统镜像分别发布</a-descriptions-item><a-descriptions-item label="升级前检查">签名、兼容性、剩余空间、WAL 与撤销职责</a-descriptions-item></template></a-descriptions><div class="collector-action-row"><a-button v-if="localTab==='rules'" @click="openAction('sync-settings')">配置规则同步</a-button><a-button v-if="localTab==='rules'" @click="openAction('rollback')">申请规则回滚</a-button><a-tooltip v-else title="当前样机没有登记系统回滚制品，需主平台提供已验证且兼容的前版本。"><a-button disabled>申请系统回滚</a-button></a-tooltip><router-link to="/page/releases"><a-button>主控平台发布中心</a-button></router-link></div><p class="field-hint">签名制品下载、引擎测试、重载或重启、实际版本回读分别记录。规则重载需要额外内存；配置与系统升级不能按规则热重载处理。</p></section>
        <section class="panel filter-panel"><div class="collector-filter"><a-input v-model:value="keyword" aria-label="检索维护任务" placeholder="任务、编号或目标版本" allow-clear/><a-select v-model:value="statusFilter" aria-label="维护任务状态" :options="['全部状态',...new Set(collector.tasks.map(task=>task.status))].map(value=>({value,label:value}))"/><a-button @click="clearFilters">清除筛选</a-button></div></section>
        <section class="panel table-panel"><div class="table-toolbar"><h2>同步与维护任务 <span class="muted">{{tasks.length}} 条</span></h2></div><a-table :columns="taskColumns" :data-source="tasks" row-key="id" :pagination="{pageSize:6,showSizeChanger:false}" :scroll="{x:1050}" size="middle"><template #bodyCell="{column,record}"><template v-if="column.key==='identity'"><button class="record-link" @click="showDetail(record)">{{record.name}}</button><small class="row-id">{{record.id}}</small></template><StatusTag v-else-if="column.key==='status'" :value="record.status"/><a-button v-else-if="column.key==='action'" type="link" size="small" @click="showDetail(record)">查看</a-button></template><template #emptyText><a-empty description="暂无符合条件的任务"><a-button v-if="hasFilters" @click="clearFilters">清除筛选</a-button></a-empty></template></a-table></section>
      </template>
      <template v-else>
        <nav class="workspace-views" aria-label="系统维护功能"><a-tabs :active-key="localTab" @change="changeTab"><a-tab-pane key="services" tab="服务与存储"/><a-tab-pane key="audits" tab="操作日志"/></a-tabs></nav>
        <template v-if="localTab==='services'"><section class="panel collector-section"><div class="panel-heading"><h2>时间与本地缓冲</h2><a-button @click="openAction('diagnostic')">生成诊断包</a-button></div><a-descriptions bordered :column="{xs:1,sm:1,md:2}" size="small"><a-descriptions-item label="主机名">{{collector.maintenance.hostname}}</a-descriptions-item><a-descriptions-item label="时区 / NTP">{{collector.maintenance.timezone}} / {{collector.maintenance.ntp}}</a-descriptions-item><a-descriptions-item label="事件 WAL 配额">{{collector.maintenance.walGiB}} GiB · 不删除未确认事件</a-descriptions-item><a-descriptions-item label="本地 PCAP 缓冲配额">{{collector.maintenance.pcapGiB}} GiB · 按空间与上传水位回收</a-descriptions-item><a-descriptions-item label="磁盘高水位">{{collector.maintenance.highWater}}%</a-descriptions-item><a-descriptions-item label="操作日志留存">{{collector.maintenance.logDays}} 天</a-descriptions-item><a-descriptions-item label="PCAP 与告警业务留存">平台默认 180 天，可自定义</a-descriptions-item><a-descriptions-item label="事件确认 / 压缩">按平台持久接收 ACK 回收 WAL / Zstandard 独立块</a-descriptions-item></a-descriptions><p class="field-hint">本地缓冲配额不代表 PCAP 仅保存短期数据；业务留存由平台策略与对象归档执行。断网期间继续检测与持久排队，容量不足时记录明确缺口，不静默覆盖未确认事件。</p></section><section class="panel table-panel"><div class="table-toolbar"><h2>本机服务</h2></div><a-table :columns="servicesColumns" :data-source="collector.services" row-key="id" :pagination="false" :scroll="{x:915}" size="middle"><template #bodyCell="{column,record}"><StatusTag v-if="column.key==='status'" :value="record.status"/><a-button v-else-if="column.key==='action'" type="link" size="small" :disabled="record.id==='runner'" @click="openAction('service',record.id)">维护</a-button></template></a-table></section></template>
        <section v-else class="panel table-panel"><div class="table-toolbar"><h2>本地操作日志</h2><span class="muted">不记录密钥与业务载荷</span></div><a-table :columns="auditColumns" :data-source="collector.audits" row-key="id" :pagination="{pageSize:8,showSizeChanger:false}" :scroll="{x:1005}" size="middle"/></section>
      </template>
    </template>
    <CollectorForm :open="actionOpen&&!localTab.startsWith('replay-')" :action="action" :service-id="serviceId" @close="closeAction" @requested="onRequested"/>
    <a-modal :open="detailOpen&&!localTab.startsWith('replay-')" :title="selectedNic?`网卡详情 · ${selectedNic.name}`:selectedTask?`任务详情 · ${selectedTask.id}`:page.id==='connection'?'设备证书与连接':`${page.title}详情`" :width="760" :footer="null" destroy-on-close class="record-detail-modal" @cancel="closeDetail">
      <template v-if="selectedNic"><a-descriptions bordered :column="{xs:1,sm:1,md:2}" size="small"><a-descriptions-item v-for="(value,label) in {'接口名称':selectedNic.name,'用途':selectedNic.role,'链路状态':selectedNic.status,'MAC 地址':selectedNic.mac,'IPv4':selectedNic.ipv4,'IPv6':selectedNic.ipv6,'驱动':selectedNic.driver,'速率':selectedNic.speed,'MTU':selectedNic.mtu,'队列数':selectedNic.queues,'GRO':selectedNic.gro,'LRO':selectedNic.lro}" :key="label" :label="label">{{value}}</a-descriptions-item></a-descriptions><p class="field-hint">链路断开时速率与流量不可观测。镜像口不承载管理 IP，实际卸载能力由驱动回读。</p></template>
      <template v-else-if="selectedTask"><a-descriptions bordered :column="{xs:1,sm:1,md:2}" size="small"><a-descriptions-item label="任务类型">{{selectedTask.type}}</a-descriptions-item><a-descriptions-item label="状态"><StatusTag :value="selectedTask.status"/></a-descriptions-item><a-descriptions-item label="来源">{{selectedTask.source}}</a-descriptions-item><a-descriptions-item label="目标 / 对象">{{selectedTask.target}}</a-descriptions-item><a-descriptions-item label="创建时间">{{selectedTask.time}}</a-descriptions-item><a-descriptions-item label="设备">{{device.id}}</a-descriptions-item><a-descriptions-item label="变更摘要" :span="2">{{selectedTask.summary}}</a-descriptions-item></a-descriptions><h3 class="collector-detail-heading">执行与回读</h3><a-timeline><a-timeline-item v-for="step in selectedTask.steps" :key="step.name" :color="step.status.startsWith('待')||step.status.includes('尚未')?'gray':'blue'"><b>{{step.name}}</b><small class="timeline-note">{{step.status}}</small></a-timeline-item></a-timeline><a-alert v-if="selectedTask.status==='等待执行回执'" type="info" show-icon message="当前申请仅保存在原型内存中；实际设备配置和生效版本保持原快照。"/></template>
      <template v-else-if="page.id==='connection'"><a-descriptions bordered :column="{xs:1,sm:1,md:2}" size="small"><a-descriptions-item label="设备身份">{{device.id}}</a-descriptions-item><a-descriptions-item label="证书状态">{{collector.certificate}}</a-descriptions-item><a-descriptions-item label="序列号">{{collector.certificateSerial}}</a-descriptions-item><a-descriptions-item label="到期时间">{{collector.certificateExpiry}}</a-descriptions-item><a-descriptions-item label="本机密钥">本机生成，私钥不回显</a-descriptions-item><a-descriptions-item label="轮换规则">签名授权、双证书过渡、撤销旧证书</a-descriptions-item><a-descriptions-item label="TLS 校验">CA 链与服务名必须匹配</a-descriptions-item><a-descriptions-item label="证书指纹">未提供真实证书指纹</a-descriptions-item></a-descriptions><p class="field-hint">连接指标为合成快照。格式检查不等于真实 DNS、TCP、TLS、注册或 gRPC 验证。</p></template>
      <template v-else><a-descriptions bordered :column="{xs:1,sm:1,md:2}" size="small"><a-descriptions-item label="采集器">{{device.name}}</a-descriptions-item><a-descriptions-item label="身份">{{device.id}}</a-descriptions-item><a-descriptions-item label="管理网络">{{collector.network.interface}} / {{collector.network.ipv4}}</a-descriptions-item><a-descriptions-item label="捕获接口">{{collector.capture.interfaces.join('、')}}</a-descriptions-item><a-descriptions-item label="实际 Agent">{{collector.agentActive}}</a-descriptions-item><a-descriptions-item label="实际引擎">{{collector.engineActive}}</a-descriptions-item><a-descriptions-item label="实际规则">{{collector.ruleActive}}</a-descriptions-item><a-descriptions-item label="最近快照">{{device.snapshot}}</a-descriptions-item></a-descriptions><p class="field-hint">当前配置仅对应此样机，不能作为其它探针的实际配置或任务回执。</p></template>
      <div class="collector-detail-footer"><a-button @click="closeDetail">关闭</a-button></div>
    </a-modal>
  </div>
  <a-result v-else status="404" title="采集器页面不存在" sub-title="请从采集器导航选择可访问的功能。"/>
</template>
