<script setup lang="ts">
import {computed,reactive,ref,watch} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {SafetyCertificateOutlined,CheckCircleOutlined} from '@ant-design/icons-vue'
import type {FormInstance} from 'ant-design-vue'
const route=useRoute();const router=useRouter();const formRef=ref<FormInstance>();const form=reactive({account:'local-admin-demo',password:'',code:''})
const mode=computed(()=>String(route.params.mode));const title=computed(()=>mode.value==='mfa'?'采集器多因素认证':mode.value==='expired'?'采集器会话已过期':'登录采集器')
watch(mode,()=>{form.password='';form.code='';document.title=`${title.value} · 星烽 StarBeacon`},{immediate:true})
async function submit(){try{await formRef.value?.validate();form.password='';void router.push(mode.value==='mfa'?'/collector/overview':'/collector/auth/mfa')}catch{}}
</script>
<template>
  <div class="auth-page collector-auth"><header><router-link to="/collector/overview" class="brand"><span class="brand-symbol"><SafetyCertificateOutlined/></span><span class="brand-copy"><b>星烽 <span>StarBeacon</span></b><small>采集器管理</small></span></router-link><router-link to="/catalog">浏览原型页面</router-link></header><div class="auth-layout"><section class="auth-intro"><h1>采集器本地管理</h1><p>在设备管理网络中完成网卡选择、网络配置、平台接入与维护。采集器主动连接主控平台，上报数据并接收授权任务。</p><div class="auth-principles"><div><CheckCircleOutlined/><span>管理网络与镜像采集网络分离</span></div><div><CheckCircleOutlined/><span>配置变更保留校验、回执和回滚</span></div><div><CheckCircleOutlined/><span>本地身份独立于平台登录和设备证书</span></div></div><small>总部核心探针 · SENSORS-0001 · 合成设备</small></section><section class="auth-card"><h2>{{title}}</h2><p>{{mode==='mfa'?'使用本地认证策略要求的第二因素继续。':mode==='expired'?'重新登录后继续查看本机配置与维护任务。':'使用已初始化的本地管理员账号。'}}</p><a-alert type="info" show-icon message="交互原型 · 不验证真实凭据。请仅输入合成账号、密码和验证码。"/><a-form v-if="mode!=='expired'" ref="formRef" :model="form" layout="vertical" @finish="submit"><template v-if="mode==='mfa'"><a-form-item label="认证验证码" name="code" :rules="[{required:true,pattern:/^\d{6}$/,message:'请输入 6 位数字验证码'}]"><a-input v-model:value="form.code" inputmode="numeric" :maxlength="6" placeholder="原型中任意 6 位数字可继续"/></a-form-item></template><template v-else><a-form-item label="本地管理员账号" name="account" :rules="[{required:true,message:'请输入本地账号'}]"><a-input v-model:value="form.account" autocomplete="off"/></a-form-item><a-form-item label="密码" name="password" :rules="[{required:true,message:'请输入合成密码'}]"><a-input-password v-model:value="form.password" autocomplete="off" placeholder="输入用于原型演示的密码"/></a-form-item></template><a-button type="primary" block html-type="submit">{{mode==='mfa'?'验证并进入':'登录'}}</a-button></a-form><a-button v-else type="primary" block @click="router.push('/collector/auth/login')">重新登录</a-button><p class="auth-card-footnote">生产设备首次启动需现场初始化管理员，未初始化前不开放远程管理；不提供通用默认密码。</p></section></div><footer>星烽 StarBeacon 采集器 · 合成示例环境</footer></div>
</template>
