<script setup lang="ts">
import {computed,ref,watch} from 'vue'
import {message} from 'ant-design-vue'
import {DownloadOutlined,SettingOutlined,LockOutlined} from '@ant-design/icons-vue'
import type {PageSpec,PreviewState} from '../models'
import {useRecords,exportCsv} from '../composables/useRecords'
import PageHeader from '../components/PageHeader.vue'
import StatePanel from '../components/StatePanel.vue'
import StatusTag from '../components/StatusTag.vue'
const props=defineProps<{page:PageSpec;state:PreviewState}>();const emit=defineEmits<{state:[value:PreviewState]}>()
const {records,save}=useRecords(props.page);const tab=ref('policies');const open=ref(false);const detail=ref(false);const selected=ref(records.value[0]!);const category=ref('全量 PCAP');const days=ref(180);const checked=ref(false);const reason=ref('');const throughput=ref(1);const replicas=ref(1);const estimateDays=ref(180)
const estimate=computed(()=>throughput.value*1e9/8*86400*estimateDays.value*replicas.value/1e15)
const impact=computed(()=>days.value<Number(selected.value.retention)?'缩短期限会使部分历史数据进入待清理范围。保全对象与活动业务对象继续保护。':days.value>Number(selected.value.retention)?'延长期限只保护当前仍存在的数据，不能恢复已经清理的数据。':'期限未改变，不产生清理范围变化。')
const columns=[{title:'数据类别',dataIndex:'name',key:'name',width:190},{title:'默认期限',dataIndex:'retention',key:'retention',width:135},{title:'存储位置',dataIndex:'storage',width:170},{title:'保全对象',dataIndex:'held',width:130},{title:'预计占用',dataIndex:'estimate',width:130},{title:'策略状态',dataIndex:'status',key:'status',width:145},{title:'操作',key:'action',width:170}]
watch(()=>props.state,state=>{open.value=state==='action';detail.value=state==='detail';if(open.value){category.value='全量 PCAP';days.value=180;checked.value=false;reason.value=''}},{immediate:true})
function edit(id:string){selected.value=records.value.find(r=>r.id===id)!;category.value=selected.value.name;days.value=Number(selected.value.retention);checked.value=false;reason.value='';open.value=true}
function close(){open.value=false;detail.value=false;if(['detail','action'].includes(props.state))emit('state','data')}
function submit(){if(!checked.value){message.error('请核对影响预览并确认。');return}if(!reason.value.trim()){message.error('请填写变更依据。');return}save({retention:days.value,status:'租户自定义',notes:reason.value},selected.value.id);close();message.success('留存期限已保存在本地示例中，未执行实际清理。')}
</script>
<template>
  <PageHeader title="留存与证据保全" description="按租户与数据类别管理期限，变更前核对容量、清理影响与保全范围。"><a-space><a-button @click="exportCsv(page,records)"><DownloadOutlined/>导出策略</a-button><a-button type="primary" @click="edit(records[0]!.id)"><SettingOutlined/>调整留存策略</a-button></a-space></PageHeader>
  <a-alert message="已启用业务数据默认均保留 180 天，包括 PCAP、告警、操作与登录日志、通知记录、文件样本和报告。当前有效配置、活动案件与证据保全对象排除自动清理。" type="info" show-icon class="page-notice"/>
  <a-tabs v-model:activeKey="tab"><a-tab-pane key="policies" tab="留存策略"><section class="panel table-panel"><div class="table-toolbar"><div><h2>分类留存</h2><span class="muted">当前租户 · 默认继承</span></div><a-tag>默认 180 天</a-tag></div><StatePanel v-if="state==='loading'||state==='error'" :state="state" @action="emit('state','data')"/><StatePanel v-else-if="state==='empty'" state="empty" title="尚未产生业务数据" description="默认留存策略已经适用；接入数据源后将显示占用与保全数量。" action="查看默认策略" @action="emit('state','data')"/><a-table v-else :columns="columns" :data-source="records" row-key="id" :pagination="false" :scroll="{x:1070}" size="middle"><template #bodyCell="{column,record,text}"><b v-if="column.key==='name'">{{text}}</b><span v-else-if="column.key==='retention'" class="tabular">{{text}} 天</span><StatusTag v-else-if="column.key==='status'" :value="text"/><a-space v-else-if="column.key==='action'"><a-button type="link" size="small" @click="detail=true;selected=record">查看</a-button><a-button type="link" size="small" @click="edit(record.id)">调整</a-button></a-space><span v-else>{{text}}</span></template></a-table></section></a-tab-pane><a-tab-pane key="holds" tab="证据保全"><section class="panel table-panel"><div class="table-toolbar"><h2>保全对象</h2><a-button type="primary" @click="detail=true"><LockOutlined/>查看保全依据</a-button></div><a-table :pagination="false" :columns="[{title:'保全编号',dataIndex:'id'},{title:'关联案件',dataIndex:'case'},{title:'证据范围',dataIndex:'scope'},{title:'到期复核',dataIndex:'review'},{title:'状态',dataIndex:'status'}]" :data-source="state==='empty'?[]:[{key:1,id:'HOLD-DEMO-001',case:'管理入口访问调查',scope:'告警、会话与原包',review:'2026-10-30',status:'保全中'},{key:2,id:'HOLD-DEMO-002',case:'异常外连核对',scope:'文件样本与报告',review:'2026-10-15',status:'待复核'}]"/></section></a-tab-pane><a-tab-pane key="cleanup" tab="清理任务"><section class="panel table-panel"><div class="table-toolbar"><h2>生命周期任务</h2><span class="muted">真实清理按水位与保全范围执行</span></div><a-table :pagination="false" :columns="[{title:'任务',dataIndex:'name'},{title:'范围',dataIndex:'scope'},{title:'资格水位',dataIndex:'watermark'},{title:'排除项',dataIndex:'exclusion'},{title:'状态',dataIndex:'status'}]" :data-source="[{key:1,name:'默认期限资格扫描',scope:'当前租户业务数据',watermark:'2026-04-03',exclusion:'活动对象与保全',status:'合成示例'}]"/></section></a-tab-pane></a-tabs>
  <section class="panel capacity-estimator"><div class="panel-heading"><h2>PCAP 容量估算</h2><span class="muted">无压缩基准 · 不作为采购承诺</span></div><div class="capacity-fields"><label><span>平均捕获速率</span><a-input-number v-model:value="throughput" :min="0.01" :max="100" :step="0.1" addon-after="Gbit/s"/></label><label><span>留存期限</span><a-input-number v-model:value="estimateDays" :min="1" :max="3650" addon-after="天"/></label><label><span>冗余倍数</span><a-input-number v-model:value="replicas" :min="1" :max="4" :step="0.1"/></label><div class="capacity-result"><span>原始数据与冗余估算</span><strong>{{estimate.toFixed(3)}} <small>PB</small></strong></div></div><p>平均速率 × 86,400 秒 × 留存天数 ÷ 8 × 冗余倍数。另计索引、对象元数据、运维余量与备份。压缩收益需实测，TLS 密文通常难以显著压缩。</p></section>
  <a-modal :open="open" title="调整留存策略" :width="820" ok-text="保存策略" cancel-text="取消" @cancel="close" @ok="submit"><div class="form-grid"><a-form-item label="数据类别"><a-select v-model:value="category" :options="records.map(r=>({value:r.name,label:r.name}))" @change="(value:string)=>{selected=records.find(r=>r.name===value)!;days=Number(selected.retention);checked=false}"/></a-form-item><a-form-item label="留存期限（天）"><a-input-number v-model:value="days" :min="1" :max="3650" style="width:100%"/></a-form-item></div><div class="impact-preview"><h3>影响预览</h3><a-descriptions :column="2" bordered size="small"><a-descriptions-item label="当前期限">{{selected.retention}} 天</a-descriptions-item><a-descriptions-item label="目标期限">{{days}} 天</a-descriptions-item><a-descriptions-item label="待清理样例">{{days<Number(selected.retention)?'24,000 条 / 2.8 TB':'无期限缩短'}}</a-descriptions-item><a-descriptions-item label="保全排除">{{selected.held}} 个对象</a-descriptions-item></a-descriptions><a-alert :message="impact" :type="days<Number(selected.retention)?'warning':'info'" show-icon style="margin-top:12px"/></div><a-form-item label="变更依据" required style="margin-top:16px"><a-textarea v-model:value="reason" :rows="3" placeholder="填写业务依据、授权与容量安排"/></a-form-item><a-checkbox v-model:checked="checked">已核对保全范围、容量和清理影响</a-checkbox><div class="modal-footnote">本原型不会删除实际数据。生产清理使用持久任务与可审计资格水位。</div></a-modal>
  <a-modal :open="detail" title="留存策略与保全范围" :width="760" :footer="null" @cancel="close"><a-descriptions :column="1" bordered><a-descriptions-item label="数据类别">{{selected.name}}</a-descriptions-item><a-descriptions-item label="留存期限">{{selected.retention}} 天</a-descriptions-item><a-descriptions-item label="继承规则">租户显式配置优先，其余继承平台默认 180 天</a-descriptions-item><a-descriptions-item label="保全范围">{{selected.held}} 个合成保全对象</a-descriptions-item><a-descriptions-item label="运行 TTL">认证、缓存与传输缓冲另有短期运行期限</a-descriptions-item></a-descriptions><a-alert message="冷热迁移与压缩不缩短留存。延长期限不能恢复已删除数据；缩短期限必须先核对影响。" type="info" show-icon style="margin-top:16px"/></a-modal>
</template>
