<script setup lang="ts">
import {ref,watch,computed} from 'vue'
import {message} from 'ant-design-vue'
import {useRouter} from 'vue-router'
import {UploadOutlined,ThunderboltOutlined,CheckCircleOutlined,SaveOutlined,PlayCircleOutlined} from '@ant-design/icons-vue'
import type {PageSpec,PreviewState} from '../models'
import {exampleRule} from '../data/fixtures'
import PageHeader from '../components/PageHeader.vue'
import StatePanel from '../components/StatePanel.vue'
import RecordForm from '../components/RecordForm.vue'
import StatusTag from '../components/StatusTag.vue'
const props=defineProps<{page:PageSpec;state:PreviewState}>();const emit=defineEmits<{state:[value:PreviewState]}>();const router=useRouter()
const inputMode=ref('natural');const description=ref('检测从外部访问业务服务器 /admin/login 的 GET 请求，要求已建立的客户端到服务端会话。');const raw=ref('GET /admin/login HTTP/1.1\r\nHost: service.example.test\r\nUser-Agent: ExampleClient/1.0\r\n\r\n');const fileName=ref('example-admin-session.pcapng');const model=ref('本地安全模型');const rule=ref(exampleRule);const generated=ref(true);const busy=ref(false);const tested=ref(false);const detail=ref(false);const formOpen=ref(false);const resultTab=ref('rule')
watch(()=>props.state,state=>{detail.value=state==='detail';formOpen.value=state==='action';if(state==='empty')generated.value=false;else if(state==='data')generated.value=true},{immediate:true})
const canTest=computed(()=>generated.value&&rule.value.length>0&&!busy.value)
async function generate(){if(inputMode.value==='natural'&&!description.value.trim()){message.error('请描述要检测的行为。');return}if(inputMode.value==='raw'&&!raw.value.trim()){message.error('请提供 HTTP Raw 样例。');return}busy.value=true;await new Promise(resolve=>setTimeout(resolve,250));rule.value=exampleRule;generated.value=true;tested.value=false;resultTab.value='rule';busy.value=false;emit('state','data');message.success('合成候选已生成，实际模型与引擎尚未接入。')}
function test(){if(!rule.value.startsWith('alert ')||!rule.value.includes('sid:')){message.error('候选缺少 alert 动作或 SID，需先修正规则。');return}tested.value=true;resultTab.value='test';message.success('已显示合成测试报告，未运行 Suricata。')}
function close(){detail.value=false;formOpen.value=false;if(['detail','action'].includes(props.state))emit('state','data')}
</script>
<template>
  <PageHeader title="AI 规则生成" description="从需求与样例形成候选规则，再完成验证、回放与签名发布。"><a-button @click="router.push('/page/rules')">规则中心</a-button></PageHeader>
  <a-alert message="当前原型生成固定合成候选，不解析上传文件、不调用模型或 Suricata。候选、测试通过与探针生效是独立状态。" type="info" show-icon class="page-notice"/>
  <a-steps :current="generated?tested?2:1:0" class="rule-steps" :items="[{title:'提供需求与证据'},{title:'生成候选规则'},{title:'测试与回放'},{title:'灰度发布'}]"/>
  <StatePanel v-if="state==='loading'||state==='error'" :state="state" @action="emit('state','data')"/>
  <div v-else class="rule-studio-grid"><section class="panel"><div class="panel-heading"><h2>输入证据</h2><a-tag>授权样本</a-tag></div><a-tabs v-model:activeKey="inputMode"><a-tab-pane key="natural" tab="自然语言"><label class="field-label">检测目标</label><a-textarea v-model:value="description" :rows="8" placeholder="描述攻击行为、协议、方向和排除条件"/></a-tab-pane><a-tab-pane key="pcap" tab="PCAP"><div class="sample-upload"><UploadOutlined/><h3>{{fileName}}</h3><p>提供包含目标行为的授权会话样例。</p><a-upload :show-upload-list="false" :before-upload="(file:File)=>{fileName=file.name;return false}"><a-button>选择 PCAP 文件</a-button></a-upload><small>原型仅记录文件名，不读取或上传内容。</small></div></a-tab-pane><a-tab-pane key="raw" tab="HTTP Raw"><label class="field-label">请求／响应样例</label><a-textarea v-model:value="raw" :rows="8" class="raw-editor" spellcheck="false"/></a-tab-pane></a-tabs><a-form layout="vertical" style="margin-top:16px"><a-form-item label="生成模型"><a-select v-model:value="model" :options="['本地安全模型','通用大模型'].map(value=>({value,label:value}))"/></a-form-item><a-form-item label="目标引擎"><a-input value="Suricata 8.0.7" readonly/></a-form-item><a-form-item label="规则变量"><a-input value="$HOME_NET / $EXTERNAL_NET" readonly/></a-form-item></a-form><a-button type="primary" block :loading="busy" @click="generate"><ThunderboltOutlined/>生成候选规则</a-button><small class="field-hint">默认只生成草稿；验证与发布分别执行。</small></section>
    <section class="panel rule-result"><div class="panel-heading"><h2>候选与验证</h2><StatusTag :value="generated?tested?'示例测试完成':'待测试':'尚未生成'"/></div><StatePanel v-if="!generated" state="empty" title="尚未生成候选规则" description="提供自然语言目标、PCAP 或 HTTP Raw 样例后，生成可审核的规则草稿。" action="生成候选规则" @action="generate"/><template v-else><a-tabs v-model:activeKey="resultTab"><a-tab-pane key="rule" tab="规则正文"><a-textarea v-model:value="rule" :rows="10" class="raw-editor" spellcheck="false"/><div class="detail-section"><h3>生成说明</h3><ul class="plain-list"><li>绑定 HTTP method 与 URI sticky buffer。</li><li>要求 flow:to_server,established，保留检测方向。</li><li>SID 为本地示例，正式保存前需检测冲突。</li><li>当前样例只表示访问管理路径，不能证明利用成功。</li></ul></div></a-tab-pane><a-tab-pane key="test" tab="测试与回放"><div v-if="tested"><a-alert message="这是合成测试结果；生产发布需运行真实目标引擎并保存测试报告。" type="info" show-icon/><a-table style="margin-top:16px" size="small" :pagination="false" :columns="[{title:'检查项',dataIndex:'name'},{title:'结果',dataIndex:'result'},{title:'说明',dataIndex:'note'}]" :data-source="[{key:1,name:'语法与变量',result:'示例通过',note:'Suricata 8.0.7 / HOME_NET'},{key:2,name:'正样本',result:'12 / 12',note:'已建立 HTTP 会话'},{key:3,name:'负样本',result:'36 / 36',note:'普通路径与其他方法'},{key:4,name:'吞吐与资源',result:'未验收',note:'需要真实 PPS / CPS / EPS 场景'},{key:5,name:'捕获覆盖',result:'需核对',note:'检查深度、丢包与 TLS 边界'}]"/></div><StatePanel v-else state="empty" title="暂无测试报告" description="候选需要完成语法、样本回放与资源验证。" action="显示示例测试" @action="test"/></a-tab-pane><a-tab-pane key="history" tab="生成记录"><a-timeline><a-timeline-item>09:42:16 创建合成生成任务</a-timeline-item><a-timeline-item>09:42:17 固定示例候选就绪</a-timeline-item><a-timeline-item color="orange">等待真实测试与人工审核</a-timeline-item></a-timeline></a-tab-pane></a-tabs><div class="rule-actions"><a-button :disabled="!canTest" @click="test"><PlayCircleOutlined/>显示示例测试</a-button><a-button type="primary" @click="formOpen=true"><SaveOutlined/>保存候选</a-button><a-button :disabled="!tested" @click="router.push('/page/releases?state=action')">进入灰度发布</a-button></div></template></section>
  </div>
  <a-modal :open="detail" title="规则生成依据" :width="760" :footer="null" @cancel="close"><a-descriptions bordered :column="1"><a-descriptions-item label="输入">{{inputMode==='natural'?'自然语言':inputMode==='raw'?'HTTP Raw':fileName}}</a-descriptions-item><a-descriptions-item label="来源">授权合成样例</a-descriptions-item><a-descriptions-item label="模型">{{model}}（未实际调用）</a-descriptions-item><a-descriptions-item label="候选">SID 1000001 / rev 1</a-descriptions-item><a-descriptions-item label="版本">引擎、提示、样本与变量分别冻结</a-descriptions-item></a-descriptions><pre class="code-block" style="margin-top:16px">{{rule}}</pre></a-modal>
  <RecordForm :open="formOpen" :page="{...page,primary:'保存候选规则',fields:[{key:'name',label:'规则名称',required:true,value:'HTTP 管理路径探测'},{key:'sid',label:'SID',type:'number',required:true,value:1000001},{key:'rule',label:'候选正文',type:'textarea',required:true,value:rule},{key:'notes',label:'审核说明',type:'textarea'}]}" @close="close" @save="()=>{close();message.success('候选已保存为本地示例草稿，未发布。')}"/>
</template>
